### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by adityaraval** [wankdanker/node-sftpjs#6]
**My GET Function**

```
"use strict";

const os = require('os');
const fs = require('fs');
const Client = require('ssh2').Client;

const key = fs.readFileSync(process.env.HOME+'/Desktop/Project-VPS/myvpsamazon.pem');


const ConnectionSettings = {
  host: '64.178.15.55',
  port: 22,
  username: 'ubuntu',
  privateKey: key
};

```

```
//Listing files from server
exports.Listing = (req,res,next) => {
  let conn = new Client();
  var remotePathToList = req.param('loc');
  //var remotePathToList = remotePathToList.toString();
  console.log(remotePathToList);
  conn.on('ready', function() {
    conn.sftp(function(err, sftp) {
    if (err) throw err;
    sftp.readdir("home/ubuntu", function(err, list) {
      if (err) throw err;
      console.dir(list);
      conn.end();
    });
  });
}).connect(ConnectionSettings);
};

```

**ERROR CODE**

if (err) throw err;
               ^

Error: No such file
    at SFTPStream._transform (/home/aditya/Desktop/Project-VPS/node_modules/ssh2-streams/lib/sftp.js:384:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/home/aditya/Desktop/Project-VPS/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at SFTPStream.Writable.write (_stream_writable.js:214:11)
    at Channel.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)

**Package.json**

```
{
  "name": "Project-VPS",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "nodemon ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "express-handlebars": "^3.0.0",
    "hbs": "~3.1.0",
    "morgan": "~1.6.1",
    "s3": "^4.4.0",
    "serve-favicon": "~2.3.0",
    "ssh2": "^0.5.0"
  }
}

```

**Comment by wankdanker** [comment]
Hi @adityaraval. Looks like your code is using `ssh2` directly and not `sftpjs` (this module). You might want to direct your question to https://github.com/mscdex/ssh2. But, my best guess is that the path you are trying to read (`home/ubuntu`) should be `/home/ubuntu`. You could always test with just `readdir('/', ...`
