### ISSUE TITLE
How to close the Client when get returns an error

### ISSUE THREAD

**Issue by janbaer** [wankdanker/node-sftpjs#7]
I've the following code for handling the case that **get** returns an error.

```
        if (error) {
          console.log('Error while downloading from sftp', error);
          client.close();
          reject(error);
          return;
        }
```

```
Error: handle is not a Buffer
    at SFTPStream.close (/Users/jan.baer/Projects/rs.addressservice/node_modules/ssh2-streams/lib/sftp.js:796:11)
    at SFTPWrapper.close (/Users/jan.baer/Projects/rs.addressservice/node_modules/ssh2/lib/SFTPWrapper.js:42:23)
    at /Users/jan.baer/Projects/rs.addressservice/import/package-downloader.js:26:16
    at ReadStream.handleError (/Users/jan.baer/Projects/rs.addressservice/node_modules/sftpjs/lib/sftp-wrapper.js:104:10)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at /Users/jan.baer/Projects/rs.addressservice/node_modules/ssh2-streams/lib/sftp.js:2611:12
    at SFTPStream._transform (/Users/jan.baer/Projects/rs.addressservice/node_modules/ssh2-streams/lib/sftp.js:387:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/jan.baer/Projects/rs.addressservice/node_modules/ssh2-streams/lib/sftp.js:170:15)
```

How can I handle gracefully and call the end command for the sftp client.

**Comment by janbaer** [comment]
I just handled the problem in another way. I just get the list and verify if the file exists before I try to **get** it. So the problem don't longer exists for me...
